-- =========================================================================
-- AUCTIONPROPERTYTODAY - STANDARDIZED CORE DATABASE SCHEMA
-- =========================================================================

-- 1. ALTER TABLE PROPERTIES MIGRATION INGRESS
-- Safely add all required standardized columns to the existing properties table.
ALTER TABLE public.properties
ADD COLUMN IF NOT EXISTS title text,
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS price bigint, -- bigint handles ultra-luxury valuations safely
ADD COLUMN IF NOT EXISTS property_type text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS location text, -- dynamic geographical description
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS area_sqft integer,
ADD COLUMN IF NOT EXISTS bedrooms integer,
ADD COLUMN IF NOT EXISTS bathrooms integer,
ADD COLUMN IF NOT EXISTS auction_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false;

-- 2. COMPLETE PROPERTIES TABLE STRUCTURE (REFERENCE SCHEMA)
-- Use this if you are creating the table from scratch.
CREATE TABLE IF NOT EXISTS public.properties (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title text NOT NULL,
    description text NOT NULL,
    price bigint NOT NULL,
    property_type text NOT NULL,
    city text NOT NULL,
    location text NOT NULL,
    state text NOT NULL,
    area_sqft integer NOT NULL,
    bedrooms integer NOT NULL,
    bathrooms integer NOT NULL,
    auction_date timestamp with time zone NOT NULL,
    is_featured boolean DEFAULT false,
    agency text DEFAULT 'State Bank of India (Distressed Assets Division)',
    amenities text[] DEFAULT '{}'::text[],
    created_at timestamp with time zone DEFAULT now()
);

-- 3. CASCADING JOINS (IMAGES & INQUIRIES)
CREATE TABLE IF NOT EXISTS public.property_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id uuid REFERENCES public.properties(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inquiries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id uuid REFERENCES public.properties(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    budget text NOT NULL,
    message text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT now()
);

-- 4. DROP NOT NULL CONSTRAINTS ON OLD LEGACY COLUMNS TO PREVENT INSERT BLOCKERS
-- If you have legacy columns in your database from previous iterations, they might be marked as NOT NULL.
-- Dropping NOT NULL on them ensures that inserting rows with ONLY the new standardized columns succeeds.
DO $$
BEGIN
    -- Check and drop NOT NULL for property_name
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_name') THEN
        ALTER TABLE public.properties ALTER COLUMN property_name DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for property_description
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_description') THEN
        ALTER TABLE public.properties ALTER COLUMN property_description DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for reservation_price
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='reservation_price') THEN
        ALTER TABLE public.properties ALTER COLUMN reservation_price DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for property_classification
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_classification') THEN
        ALTER TABLE public.properties ALTER COLUMN property_classification DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for location
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='location') THEN
        ALTER TABLE public.properties ALTER COLUMN location DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for built_area
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='built_area') THEN
        ALTER TABLE public.properties ALTER COLUMN built_area DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for bhk_configuration
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='bhk_configuration') THEN
        ALTER TABLE public.properties ALTER COLUMN bhk_configuration DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for bathroom_configuration
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='bathroom_configuration') THEN
        ALTER TABLE public.properties ALTER COLUMN bathroom_configuration DROP NOT NULL;
    END IF;
END $$;

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Enable Row Level Security (RLS) on all active tables
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Safely drop existing policies before recreating them to avoid duplicates
DROP POLICY IF EXISTS "Allow public read access to properties" ON public.properties;
DROP POLICY IF EXISTS "Allow authenticated admin full control on properties" ON public.properties;
DROP POLICY IF EXISTS "Allow public read access to property images" ON public.property_images;
DROP POLICY IF EXISTS "Allow authenticated admin full control on property images" ON public.property_images;
DROP POLICY IF EXISTS "Allow public to submit inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Allow authenticated admin full control on inquiries" ON public.inquiries;

-- A. Properties Policies
CREATE POLICY "Allow public read access to properties"
    ON public.properties FOR SELECT USING (true);

CREATE POLICY "Allow authenticated admin full control on properties"
    ON public.properties FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- B. Property Images Policies
CREATE POLICY "Allow public read access to property images"
    ON public.property_images FOR SELECT USING (true);

CREATE POLICY "Allow authenticated admin full control on property images"
    ON public.property_images FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- C. Inquiries Policies
CREATE POLICY "Allow public to submit inquiries"
    ON public.inquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated admin full control on inquiries"
    ON public.inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- 6. AUTHORIZED CLIENT ACCESS CONTROL SCHEMA [NEW]
CREATE TABLE IF NOT EXISTS public.authorized_users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to authorized_users" ON public.authorized_users;
DROP POLICY IF EXISTS "Allow authenticated admin full control on authorized_users" ON public.authorized_users;

-- Standard clients need to read this table to authenticate their passwords at login.
-- Admins need full CRUD control.
CREATE POLICY "Allow public read access to authorized_users"
    ON public.authorized_users FOR SELECT USING (true);

CREATE POLICY "Allow authenticated admin full control on authorized_users"
    ON public.authorized_users FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- 7. PAID PROPERTY ACCESS SCHEMA [NEW]
CREATE TABLE IF NOT EXISTS public.property_access (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    property_id uuid NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    razorpay_payment_id text NOT NULL,
    amount bigint NOT NULL,
    user_email text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.property_access ENABLE ROW LEVEL SECURITY;

-- Drop any legacy/duplicate policies
DROP POLICY IF EXISTS "Users can view their own property access records" ON public.property_access;
DROP POLICY IF EXISTS "Users can insert their own property access records" ON public.property_access;
DROP POLICY IF EXISTS "Admin can view all property access records" ON public.property_access;

-- RLS Policy: Users can view purchase records corresponding to their user_id, or anonymous guests
CREATE POLICY "Users can view their own property access records"
    ON public.property_access FOR SELECT USING (
      auth.uid() = user_id 
      OR auth.uid() IS NULL
    );

-- RLS Policy: Users can insert purchase records corresponding to their user_id, or anonymous guests
CREATE POLICY "Users can insert their own property access records"
    ON public.property_access FOR INSERT WITH CHECK (
      auth.uid() = user_id 
      OR auth.uid() IS NULL
    );

-- RLS Policy: Admin can view all property access records
CREATE POLICY "Admin can view all property access records"
    ON public.property_access FOR SELECT USING (
      (select auth.jwt() ->> 'email') IN ('admin@auctionproperty.today', 'liaison@auctionproperty.today', 'escrow@auctionproperty.today', 'iammanishgarg@gmail.com')
    );
-- 8. PROPERTY ACCESS GATING PASSWORD SYSTEM [NEW]
-- Add access password column to properties table
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS access_password text;

-- Create secure verification & unlock log function
CREATE OR REPLACE FUNCTION public.verify_and_unlock_property(
  p_property_id uuid,
  p_password text,
  p_user_email text
)
RETURNS boolean SECURITY DEFINER AS $$
DECLARE
  v_correct_password text;
  v_user_id uuid;
BEGIN
  -- 1. Fetch password for target property
  SELECT access_password INTO v_correct_password FROM public.properties WHERE id = p_property_id;
  
  -- 2. Verify match
  IF v_correct_password = p_password THEN
    -- Get user id if logged in
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
      v_user_id := '00000000-0000-0000-0000-000000000000'::uuid;
    END IF;
    
    -- Log unlock event in property_access (storing 'password_unlock' as payment ID and 0 amount)
    INSERT INTO public.property_access (user_id, property_id, razorpay_payment_id, amount, user_email)
    VALUES (v_user_id, p_property_id, 'password_unlock', 0, p_user_email)
    ON CONFLICT DO NOTHING;
    
    RETURN true;
  ELSE
    RETURN false;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 9. PROPERTY DOCUMENTS SCHEMA [NEW]
CREATE TABLE IF NOT EXISTS public.property_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id uuid REFERENCES public.properties(id) ON DELETE CASCADE,
    document_url text NOT NULL,
    document_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.property_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to property documents" ON public.property_documents;
DROP POLICY IF EXISTS "Allow authenticated admin full control on property documents" ON public.property_documents;

-- Standard clients can read property documents.
CREATE POLICY "Allow public read access to property documents"
    ON public.property_documents FOR SELECT USING (true);

-- Authenticated admins have full CRUD control.
CREATE POLICY "Allow authenticated admin full control on property documents"
    ON public.property_documents FOR ALL TO authenticated USING (true) WITH CHECK (true);

