-- =========================================================================
-- AUCTIONPROPERTYTODAY - STANDARDIZED CORE DATABASE SCHEMA
-- =========================================================================

-- 1. ALTER TABLE PROPERTIES MIGRATION INGRESS
-- Safely add all required standardized columns to the existing properties table.
ALTER TABLE public.properties
ADD COLUMN IF NOT EXISTS title text,
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS price bigint, -- bigint handles ultra-luxury valuations safely
ADD COLUMN IF NOT EXISTS property_type text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS location text, -- dynamic geographical description
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS area_sqft integer,
ADD COLUMN IF NOT EXISTS bedrooms integer,
ADD COLUMN IF NOT EXISTS bathrooms integer,
ADD COLUMN IF NOT EXISTS auction_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false;

-- 2. COMPLETE PROPERTIES TABLE STRUCTURE (REFERENCE SCHEMA)
-- Use this if you are creating the table from scratch.
CREATE TABLE IF NOT EXISTS public.properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL,
    price bigint NOT NULL,
    property_type text NOT NULL,
    city text NOT NULL,
    location text NOT NULL,
    state text NOT NULL,
    area_sqft integer NOT NULL,
    bedrooms integer NOT NULL,
    bathrooms integer NOT NULL,
    auction_date timestamp with time zone NOT NULL,
    is_featured boolean DEFAULT false,
    agency text DEFAULT 'State Bank of India (Distressed Assets Division)',
    amenities text[] DEFAULT '{}'::text[],
    created_at timestamp with time zone DEFAULT now()
);

-- 3. CASCADING JOINS (IMAGES & INQUIRIES)
CREATE TABLE IF NOT EXISTS public.property_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inquiries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    budget text NOT NULL,
    message text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT now()
);

-- 4. DROP NOT NULL CONSTRAINTS ON OLD LEGACY COLUMNS TO PREVENT INSERT BLOCKERS
-- If you have legacy columns in your database from previous iterations, they might be marked as NOT NULL.
-- Dropping NOT NULL on them ensures that inserting rows with ONLY the new standardized columns succeeds.
DO $$
BEGIN
    -- Check and drop NOT NULL for property_name
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_name') THEN
        ALTER TABLE public.properties ALTER COLUMN property_name DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for property_description
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_description') THEN
        ALTER TABLE public.properties ALTER COLUMN property_description DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for reservation_price
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='reservation_price') THEN
        ALTER TABLE public.properties ALTER COLUMN reservation_price DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for property_classification
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='property_classification') THEN
        ALTER TABLE public.properties ALTER COLUMN property_classification DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for location
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='location') THEN
        ALTER TABLE public.properties ALTER COLUMN location DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for built_area
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='built_area') THEN
        ALTER TABLE public.properties ALTER COLUMN built_area DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for bhk_configuration
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='bhk_configuration') THEN
        ALTER TABLE public.properties ALTER COLUMN bhk_configuration DROP NOT NULL;
    END IF;

    -- Check and drop NOT NULL for bathroom_configuration
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='properties' AND column_name='bathroom_configuration') THEN
        ALTER TABLE public.properties ALTER COLUMN bathroom_configuration DROP NOT NULL;
    END IF;
END $$;

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Enable Row Level Security (RLS) on all active tables
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Safely drop existing policies before recreating them to avoid duplicates
DROP POLICY IF EXISTS "Allow public read access to properties" ON public.properties;
DROP POLICY IF EXISTS "Allow authenticated admin full control on properties" ON public.properties;
DROP POLICY IF EXISTS "Allow public read access to property images" ON public.property_images;
DROP POLICY IF EXISTS "Allow authenticated admin full control on property images" ON public.property_images;
DROP POLICY IF EXISTS "Allow public to submit inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Allow authenticated admin full control on inquiries" ON public.inquiries;

-- A. Properties Policies
CREATE POLICY "Allow public read access to properties"
    ON public.properties FOR SELECT USING (true);

CREATE POLICY "Allow authenticated admin full control on properties"
    ON public.properties FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- B. Property Images Policies
CREATE POLICY "Allow public read access to property images"
    ON public.property_images FOR SELECT USING (true);

CREATE POLICY "Allow authenticated admin full control on property images"
    ON public.property_images FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- C. Inquiries Policies
CREATE POLICY "Allow public to submit inquiries"
    ON public.inquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated admin full control on inquiries"
    ON public.inquiries FOR ALL TO authenticated USING (true) WITH CHECK (true);

